### ISSUE TITLE
Not necessary anymore for DT2W

### ISSUE THREAD

**Issue by maciek134** [ivoxavier/fajitatweaks#3]
Hey, since DT2W is now [supported in the OS][1], the app should no longer be necessary (unless ofc you have other tweaks for this device in mind).

[1]: https://docs.ubports.com/en/latest/porting/configure_test_fix/device_info/Repowerd.html

**Comment by ivoxavier** [comment]
Hi maciek, yes I'll remove it from the store, does not make sense anymore.

Thank you :)
